config/routes.rb
Rails.application.routes.draw do
  resources :posts
  devise_for :users
  root to: "cooks#index"
  get 'favorites/index'
  get 'posts/index'
  get 'cooks/index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :cooks
  resources :posts
  resources :favarites
  
  post 'favorite/:id' => 'favorites#create', as: 'create_favorite'
  post 'favorite/:id' => 'favorites#destroy', as: 'destroy_favorite'
  
  resources :users, only: [:show]
end  
  

app/models/cook.rb
class Cook < ApplicationRecord
    has_many :favorites
    has_many :users
    has_many :posts
end

app/controllers/cooks_controller.rb
class CooksController < ApplicationController
  
  #ログインしている人だけが投稿を行えるように[authenticate_user!]を使用
  before_action :authenticate_user!, except: :index
  
  #他人に編集ができないようした（投稿者自身が編集ができるようにした)
  before_action :correct_user_cook, only: [:edit, :update]
  
  def index
    @cooks = Cook.all
    @posts = Post.all
  end
  
  def new
    @cook = Cook.new
  end
  
  def create
    @cook = Cook.new(params.require(:cook).permit(:name, :poin, :ingredient, :recipe).merge(user_id: current_user.id))
    if @cook.save
      flash[:notice] = "料理の新規登録しました"
      redirect_to :cooks
    else
      render "new"
    end
  end
  
  def show
    @cook = Cook.find(params[:id])
    @post = Post.new
    @posts = Post.where(cook_id: @cook.id)
  end
  
  def edit
    @cook = Cook.find(params[:id])
  end
  
  def update
    @cook = Cook.find(params[:id])
    if @cook.update(params.require(:cook).permit(:name, :poin, :ingredient, :recipe).merge(user_id: current_user.id))
      flash[:notice] = "料理の情報を更新しました"
      redirect_to :cooks
    else
      render "edit"
    end
  end
  
  def destroy
    @cook = Cook.find(params[:id])
    @cook.destroy
    flash[:notice] = "料理を削除しました"
    redirect_to :cooks
  end
  
  private
  def correct_user_cook
    @cook = Cook.find(params[:id])
    @user = @cook.user_id
    redirect_to(cooks_path) unless @user == current_user.id
  end
end

app/helpers/cooks_helper.rb
module CooksHelper
end

app/views/cooks/edit.html.erb
<h3>料理の編集</h3>

<%= form_with model: @cook do |f| %>
    <table>
        <tr>
            <th><%= f.label :name, "料理名" %></th>
            <td><%= f.text_area :name %></td>
        </tr>
        <tr>
            <th><%= f.label :poin, "作る際のポイント" %></th>
            <td><%= f.text_area :poin %></td>
        </tr>
        <tr>
            <th><%= f.label :ingredient, "材料" %></th>
            <td><%= f.text_area :ingredient %></td>
        </tr>
        <tr>
            <th><%= f.label :recipe, "作り方" %></th>
            <td><%= f.text_area :recipe %></td>
        </tr>
    </table>
    <div>
        <ul>
            <li><%= f.submit "編集を完了する" %></li>
            <li><%= link_to "料理の一覧表に戻る", cooks_path %></li>
            <li><%= link_to "投稿の一覧表に戻る", posts_path %></li>
        </ul>
    </div>
<% end %>

app/views/cooks/index.html.erb
<% if user_signed_in? %>
  <%= link_to 'ログアウト', destroy_user_session_path, method: :delete %>
  <%= link_to 'お気に入り一覧', user_path(current_user.id) %>
  <%= link_to '料理の投稿ページ', new_cook_path %>
<% else %>
  <%= link_to 'ログイン', new_user_session_path %>
  <%= link_to '新規登録', new_user_registration_path %>
<% end %>


<h1>料理の一覧表</h1>

<% if flash[:notice] %>
    <p class="notice"><%= flash[:notice] %></p>
<% end %>

<table>
    <thead>
        <tr>
            <th>ID</th>
            <th>料理名</th>
            <th>料理の作る際のポイント</th>
            <th>材料</th>
            <th>作り方</th>
            <th>詳細</th>
            <th>編集</th>
            <th>削除</th>
            <th>お気に入り</th>
        </tr>
    </thead>
    <tbody>
        <% @cooks.each do |cook| %>
                <tr>
                    <td><%= cook.id %></td>
                    <td><%= cook.name %></td>
                    <td><%= cook.poin %></td>
                    <td><%= cook.ingredient %></td>
                    <td><%= cook.recipe %></td>
                    <td><%= link_to "詳細", cook %></td>
                    <td><%= link_to "編集" , [:edit, cook] %></td>
                    <td>
                        <%= link_to "削除", cook, method: :delete, data:{confirm:"本当に削除しますか？"} %>
                    </td>
                    <td>
                        <% if user_signed_in? && current_user != cook.users %>
                            <% if current_user.favorite_find(cook.id) %>
                              <%= link_to 'お気に入りからはずす', destroy_favorite_path(cook.id), method: :delete %>
                            <% else %>
                              <%= link_to 'お気に入り登録する', create_favorite_path(cook.id), method: :post %>
                            <% end %>
                        <% end %>
                    </td>
                </tr>
        <% end %>
    </tbody>
</table>

<p><%= link_to "料理の新規登録", new_cook_path %></p>
<p><%= link_to "投稿一覧表", posts_path %></p>

app/views/cooks/new.html.erb
<h3>料理の新規登録</h3>

<%= form_with model: @cook, local: true do |f| %>
    <table>
        <tr>
            <th><%= f.label :name, "料理名" %></th>
            <td><%= f.text_area :name %></td>
        </tr>
        <tr>
            <th><%= f.label :poin, "作る際のポイント" %></th>
            <td><%= f.text_area :poin %></td>
        </tr>
        <tr>
            <th><%= f.label :ingredient, "材料" %></th>
            <td><%= f.text_area :ingredient %></td>
        </tr>
        <tr>
            <th><%= f.label :recipe, "作り方" %></th>
            <td><%= f.text_area :recipe %></td>
        </tr>
    </table>
    
    <div>
        <ul>
            <li><%= f.submit "登録完了" %></li>
            <li><%= link_to "料理の一覧表に戻る", cooks_path %></li>
            <li><%= link_to "投稿の一覧表に戻る", posts_path %></li>
        </ul>
    </div>
<% end %>

app/views/cooks/show.html.erb
<h3>料理の詳細ページ</h3>

<table>
    <tr>
        <th>料理名</th>
        <td><%= @cook.name %></td>
    </tr>
    <tr>
        <th>作る際のポイント</th>
        <td><%= @cook.poin %></td>
    </tr>
    <tr>
        <th>材料</th>
        <td><%= @cook.ingredient %></td>
    </tr>
    <tr>
        <th>作り方</th>
        <td><%= @cook.recipe %></td>
    </tr>
</table>

<div>
    <ul>
        <li><%= link_to "料理の一覧表の戻る", cooks_path %></li>
        <li><%= link_to "投稿一覧表に戻る", posts_path %></li>
    </ul>
</div>

<h3>新規投稿</h3>
 
    <%= form_with model: @post do |f| %>
      <table>
        <tr>
          <th><%= f.label :content, "投稿内容" %></th>
          <td><%= f.text_area :content, class:"posts-content" %></td>
        </tr>
      </table>
      <%= f.hidden_field :cook_id, value: @cook.id %>
      <%= f.hidden_field :user_id, value: @user_id %>
      <div>
        <ul>
          <li><%= f.submit "投稿を完了する"%></li>
        </ul>
      </div>
    <% end %>
 

<h3>投稿一覧表</h3>

<table>
    <thead>
        <tr>
            <th>投稿内容</th>
            <th>更新日時</th>
            <th>投稿日時</th>
            <th>投稿者</th>
        </tr>
    </thead>
    
    <tbody>
        <% @posts.each do |post| %>
            <tr>
                <td><%= post.content %></td>
                <td><%= post.updated_at.to_s(:datetime_jp) %></td>
                <td><%= post.created_at.to_s(:datetime_jp) %></td>
                <td><%= post.user_id %></td>
            </tr>
        <% end %>
    </tbody>
</table>