config/routes.rb
Rails.application.routes.draw do
  resources :posts
  devise_for :users
  root to: "cooks#index"
  get 'favorites/index'
  get 'posts/index'
  get 'cooks/index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :cooks
  resources :posts
  resources :favarites
  
  post 'favorite/:id' => 'favorites#create', as: 'create_favorite'
  post 'favorite/:id' => 'favorites#destroy', as: 'destroy_favorite'
  
  resources :users, only: [:show]
end  
  

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :cook
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, except: :indexs
  
  #他人に編集ができないようした（投稿者自身が編集ができるようにした)
  before_action :correct_user_post, only: [:edit, :update]
  
  def index
    @posts = Post.all
  end
  
  def new
  end
  
  def create
    @post = Post.new(params.require(:post).permit(:content, :cook_id, :user_id).merge(user_id: current_user.id))
    if @post.save
      flash[:notice] = "新規投稿しました"
      redirect_to :posts
    else
      render "posts"
    end
  end
  
  def show
    @post = Post.find(params[:id])
  end
  
  def edit
    @post = Post.find(params[:id])
  end
  
  def update
    @post = Post.find(params[:id])
    if @post.update(params.require(:post).permit(:content, :cook_id, :user_id))
      flash[:notice] = "投稿を更新しました"
      redirect_to :posts
    else
      render "edit"
    end
  end
  
  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    flash[:notice] = "投稿を削除しました"
    redirect_to :posts
  end
  
  private
  def correct_user_post
    @post = Post.find(params[:id])
    @user = @post.user_id
    redirect_to(posts_path) unless @user == current_user.id
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/edit.html.erb
<h3>投稿編集</h3>

<%= form_with model: @post do |f| %>
    <table>
        <tr>
            <th><%= f.label :content, "投稿内容" %></th>
            <td><%= f.text_area :content, class:"post-content" %></td>
        </tr>
    </table>
    <div>
        <ul>
            <li><%= f.submit "編集を完了する" %></li>
            <li><%= link_to "料理一覧表に戻る", :cooks %></li>
            <li><%= link_to "投稿の一覧表に戻る", posts_path %></li>
        </ul>
    </div>
<% end %>

app/views/posts/index.html.erb
<% if user_signed_in? %>
  <%= link_to 'ログアウト', destroy_user_session_path, method: :delete %>
  <%= link_to '投稿ページへ', new_post_path %>
<% else %>
  <%= link_to 'ログイン', new_user_session_path %>
  <%= link_to '新規登録', new_user_registration_path %>
<% end %>

<h3>投稿一覧表</h3>
<table>
    <thead>
        <tr>
            <th>投稿内容</th>
            <th>投稿日時</th>
            <th>更新日</th>
            <th>投稿者</th>
            <th>参照</th>
            <th>編集</th>
            <th>削除</th>
        </tr>
    </thead>
    <tbody>
        <% @posts.each do |post| %>
            <tr>
                <td><%= post.content %></td>
                <td><%= post.created_at.to_s(:datetime_jp) %></td>
                <td><%= post.updated_at.to_s(:datetime_jp) %></td>
                <td><%= post.user_id %></td>
                <td>
                    <%= link_to "参照", post %>
                </td>
                <td>
                    <%= link_to "編集", [:edit, post] %>
                </td>
                <td>
                    <%= link_to "削除", post, method: :delete, data: {confirm: "本当に削除しますか?"} %>
                </td>
            </tr>
        <% end %>
    </tbody>
</table>

<p><%= link_to "料理の一覧表" , cooks_path %></p>

app/views/posts/show.html.erb
<h3>投稿詳細</h3>

<table>
    <tr>
        <th>投稿内容</th>
        <td><pre><%= @post.content %></pre></td>
    </tr>
    <tr>
        <th>更新日時</th>
        <td><%= @post.updated_at.to_s(:datetime_jp) %></td>
    </tr>
    <tr>
        <th>投稿日時</th>
        <td><%= @post.created_at.to_s(:datetime_jp) %></td>
    </tr>
    <tr>
        <th>投稿者</th>
        <td><%= @post.user_id %></td>
    </tr>
</table>

<h3>料理の詳細</h3>

<table>
    <tr>
        <th>料理名</th>
        <td><%= @post.cook.name %></td>
    </tr>
    <tr>
        <th>作る際のポイント</th>
        <td><%= @post.cook.poin %></td>
    </tr>
    <tr>
        <th>材料</th>
        <td><%= @post.cook.ingredient %></td>
    </tr>
    <tr>
        <th>作り方</th>
        <td><%= @post.cook.recipe %></td>
    </tr>
</table>

<div>
    <ul>
        <li><%= link_to "料理の一覧表" , cooks_path %></li>
    </ul>
</div>